#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v4
# autospec commit: e738c51
#
Name     : R-deldir
Version  : 2.0.4
Release  : 71
URL      : https://cran.r-project.org/src/contrib/deldir_2.0-4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/deldir_2.0-4.tar.gz
Summary  : Delaunay Triangulation and Dirichlet (Voronoi) Tessellation
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-deldir-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
or Voronoi tessellation (with respect to the entire plane) of
	a planar point set. Plots triangulations and tessellations in
	various ways.  Clips tessellations to sub-windows. Calculates
	perimeters of tessellations.  Summarises information about
	the tiles of the tessellation.	Calculates the centroidal
	Voronoi (Dirichlet) tessellation using Lloyd's algorithm.

%package lib
Summary: lib components for the R-deldir package.
Group: Libraries

%description lib
lib components for the R-deldir package.


%prep
%setup -q -n deldir
pushd ..
cp -a deldir buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1709136892

%install
export SOURCE_DATE_EPOCH=1709136892
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-va/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/deldir/DESCRIPTION
/usr/lib64/R/library/deldir/INDEX
/usr/lib64/R/library/deldir/Meta/Rd.rds
/usr/lib64/R/library/deldir/Meta/data.rds
/usr/lib64/R/library/deldir/Meta/features.rds
/usr/lib64/R/library/deldir/Meta/hsearch.rds
/usr/lib64/R/library/deldir/Meta/links.rds
/usr/lib64/R/library/deldir/Meta/nsInfo.rds
/usr/lib64/R/library/deldir/Meta/package.rds
/usr/lib64/R/library/deldir/NAMESPACE
/usr/lib64/R/library/deldir/R/deldir
/usr/lib64/R/library/deldir/R/deldir.rdb
/usr/lib64/R/library/deldir/R/deldir.rdx
/usr/lib64/R/library/deldir/READ_ME
/usr/lib64/R/library/deldir/code.discarded/collinChk.R
/usr/lib64/R/library/deldir/code.discarded/collincheck.f
/usr/lib64/R/library/deldir/code.discarded/collincheck.r
/usr/lib64/R/library/deldir/code.discarded/fexitc.c
/usr/lib64/R/library/deldir/code.discarded/fexitf.f
/usr/lib64/R/library/deldir/code.discarded/fexitf.r
/usr/lib64/R/library/deldir/code.discarded/ind.dup.R
/usr/lib64/R/library/deldir/code.discarded/inddup.r
/usr/lib64/R/library/deldir/code.discarded/init.c
/usr/lib64/R/library/deldir/code.discarded/intri.r.save
/usr/lib64/R/library/deldir/code.discarded/triang.list.R.save
/usr/lib64/R/library/deldir/code.discarded/trigraf.c
/usr/lib64/R/library/deldir/code.discarded/trigraf.r
/usr/lib64/R/library/deldir/code.discarded/trigraf1.r.save
/usr/lib64/R/library/deldir/code.discarded/xsucc.f
/usr/lib64/R/library/deldir/data/Rdata.rdb
/usr/lib64/R/library/deldir/data/Rdata.rds
/usr/lib64/R/library/deldir/data/Rdata.rdx
/usr/lib64/R/library/deldir/help/AnIndex
/usr/lib64/R/library/deldir/help/aliases.rds
/usr/lib64/R/library/deldir/help/deldir.rdb
/usr/lib64/R/library/deldir/help/deldir.rdx
/usr/lib64/R/library/deldir/help/macros/defns.Rd
/usr/lib64/R/library/deldir/help/paths.rds
/usr/lib64/R/library/deldir/html/00Index.html
/usr/lib64/R/library/deldir/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/deldir/libs/deldir.so
/usr/lib64/R/library/deldir/libs/deldir.so
