#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
#
Name     : R-deldir
Version  : 1.0.9
Release  : 66
URL      : https://cran.r-project.org/src/contrib/deldir_1.0-9.tar.gz
Source0  : https://cran.r-project.org/src/contrib/deldir_1.0-9.tar.gz
Summary  : Delaunay Triangulation and Dirichlet (Voronoi) Tessellation
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-deldir-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
or Voronoi tessellation (with respect to the entire plane) of
	a planar point set. Plots triangulations and tessellations in
	various ways.  Clips tessellations to sub-windows. Calculates
	perimeters of tessellations.  Summarises information about
	the tiles of the tessellation.	Calculates the centroidal
	Voronoi (Dirichlet) tessellation using Lloyd's algorithm.

%package lib
Summary: lib components for the R-deldir package.
Group: Libraries

%description lib
lib components for the R-deldir package.


%prep
%setup -q -n deldir
pushd ..
cp -a deldir buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1684339795

%install
export SOURCE_DATE_EPOCH=1684339795
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/deldir/DESCRIPTION
/usr/lib64/R/library/deldir/INDEX
/usr/lib64/R/library/deldir/Meta/Rd.rds
/usr/lib64/R/library/deldir/Meta/data.rds
/usr/lib64/R/library/deldir/Meta/features.rds
/usr/lib64/R/library/deldir/Meta/hsearch.rds
/usr/lib64/R/library/deldir/Meta/links.rds
/usr/lib64/R/library/deldir/Meta/nsInfo.rds
/usr/lib64/R/library/deldir/Meta/package.rds
/usr/lib64/R/library/deldir/NAMESPACE
/usr/lib64/R/library/deldir/R/deldir
/usr/lib64/R/library/deldir/R/deldir.rdb
/usr/lib64/R/library/deldir/R/deldir.rdx
/usr/lib64/R/library/deldir/READ_ME
/usr/lib64/R/library/deldir/Ratfor/acchk.r
/usr/lib64/R/library/deldir/Ratfor/addpt.r
/usr/lib64/R/library/deldir/Ratfor/adjchk.r
/usr/lib64/R/library/deldir/Ratfor/binsrt.r
/usr/lib64/R/library/deldir/Ratfor/circen.r
/usr/lib64/R/library/deldir/Ratfor/cross.r
/usr/lib64/R/library/deldir/Ratfor/delet.r
/usr/lib64/R/library/deldir/Ratfor/delet1.r
/usr/lib64/R/library/deldir/Ratfor/delout.r
/usr/lib64/R/library/deldir/Ratfor/delseg.r
/usr/lib64/R/library/deldir/Ratfor/dirout.r
/usr/lib64/R/library/deldir/Ratfor/dirseg.r
/usr/lib64/R/library/deldir/Ratfor/dldins.r
/usr/lib64/R/library/deldir/Ratfor/initad.r
/usr/lib64/R/library/deldir/Ratfor/insrt.r
/usr/lib64/R/library/deldir/Ratfor/insrt1.r
/usr/lib64/R/library/deldir/Ratfor/intri.r
/usr/lib64/R/library/deldir/Ratfor/locn.r
/usr/lib64/R/library/deldir/Ratfor/makefor
/usr/lib64/R/library/deldir/Ratfor/master.r
/usr/lib64/R/library/deldir/Ratfor/mnnd.r
/usr/lib64/R/library/deldir/Ratfor/pred.r
/usr/lib64/R/library/deldir/Ratfor/qtest.r
/usr/lib64/R/library/deldir/Ratfor/qtest1.r
/usr/lib64/R/library/deldir/Ratfor/stoke.r
/usr/lib64/R/library/deldir/Ratfor/succ.r
/usr/lib64/R/library/deldir/Ratfor/swap.r
/usr/lib64/R/library/deldir/Ratfor/testeq.r
/usr/lib64/R/library/deldir/Ratfor/triar.r
/usr/lib64/R/library/deldir/Ratfor/trifnd.r
/usr/lib64/R/library/deldir/SavedRatfor/acchk.r
/usr/lib64/R/library/deldir/SavedRatfor/addpt.r
/usr/lib64/R/library/deldir/SavedRatfor/adjchk.r
/usr/lib64/R/library/deldir/SavedRatfor/binsrt.r
/usr/lib64/R/library/deldir/SavedRatfor/circen.r
/usr/lib64/R/library/deldir/SavedRatfor/collincheck.r
/usr/lib64/R/library/deldir/SavedRatfor/cross.r
/usr/lib64/R/library/deldir/SavedRatfor/crossutil.r
/usr/lib64/R/library/deldir/SavedRatfor/delet.r
/usr/lib64/R/library/deldir/SavedRatfor/delet1.r
/usr/lib64/R/library/deldir/SavedRatfor/delout.r
/usr/lib64/R/library/deldir/SavedRatfor/delseg.r
/usr/lib64/R/library/deldir/SavedRatfor/dirout.r
/usr/lib64/R/library/deldir/SavedRatfor/dirseg.r
/usr/lib64/R/library/deldir/SavedRatfor/dldins.r
/usr/lib64/R/library/deldir/SavedRatfor/initad.r
/usr/lib64/R/library/deldir/SavedRatfor/insrt.r
/usr/lib64/R/library/deldir/SavedRatfor/insrt1.r
/usr/lib64/R/library/deldir/SavedRatfor/intri.r
/usr/lib64/R/library/deldir/SavedRatfor/locn.r
/usr/lib64/R/library/deldir/SavedRatfor/master.r
/usr/lib64/R/library/deldir/SavedRatfor/mnnd.r
/usr/lib64/R/library/deldir/SavedRatfor/pred.r
/usr/lib64/R/library/deldir/SavedRatfor/qtest.r
/usr/lib64/R/library/deldir/SavedRatfor/qtest1.r
/usr/lib64/R/library/deldir/SavedRatfor/stoke.r
/usr/lib64/R/library/deldir/SavedRatfor/succ.r
/usr/lib64/R/library/deldir/SavedRatfor/swap.r
/usr/lib64/R/library/deldir/SavedRatfor/testeq.r
/usr/lib64/R/library/deldir/SavedRatfor/triar.r
/usr/lib64/R/library/deldir/SavedRatfor/trifnd.r
/usr/lib64/R/library/deldir/code.discarded/collinChk.R
/usr/lib64/R/library/deldir/code.discarded/collincheck.f
/usr/lib64/R/library/deldir/code.discarded/collincheck.r
/usr/lib64/R/library/deldir/code.discarded/fexitc.c
/usr/lib64/R/library/deldir/code.discarded/fexitf.f
/usr/lib64/R/library/deldir/code.discarded/fexitf.r
/usr/lib64/R/library/deldir/code.discarded/ind.dup.R
/usr/lib64/R/library/deldir/code.discarded/inddup.r
/usr/lib64/R/library/deldir/code.discarded/init.c
/usr/lib64/R/library/deldir/code.discarded/intri.r.save
/usr/lib64/R/library/deldir/code.discarded/triang.list.R.save
/usr/lib64/R/library/deldir/code.discarded/trigraf.c
/usr/lib64/R/library/deldir/code.discarded/trigraf.r
/usr/lib64/R/library/deldir/code.discarded/trigraf1.r.save
/usr/lib64/R/library/deldir/code.discarded/xsucc.f
/usr/lib64/R/library/deldir/data/Rdata.rdb
/usr/lib64/R/library/deldir/data/Rdata.rds
/usr/lib64/R/library/deldir/data/Rdata.rdx
/usr/lib64/R/library/deldir/help/AnIndex
/usr/lib64/R/library/deldir/help/aliases.rds
/usr/lib64/R/library/deldir/help/deldir.rdb
/usr/lib64/R/library/deldir/help/deldir.rdx
/usr/lib64/R/library/deldir/help/macros/defns.Rd
/usr/lib64/R/library/deldir/help/paths.rds
/usr/lib64/R/library/deldir/html/00Index.html
/usr/lib64/R/library/deldir/html/R.css

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/deldir/libs/deldir.so
/usr/lib64/R/library/deldir/libs/deldir.so.avx2
/usr/lib64/R/library/deldir/libs/deldir.so.avx512
